# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/qinchenchong/workspace/QSniffer/QSniffer.ui'
#
# Created: Tue Oct 23 01:24:35 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 687)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.pktGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.pktGroupBox.setGeometry(QtCore.QRect(250, 73, 701, 600))
        self.pktGroupBox.setObjectName(_fromUtf8("pktGroupBox"))
        self.pktTableWidget = QtGui.QTableWidget(self.pktGroupBox)
        self.pktTableWidget.setGeometry(QtCore.QRect(10, 31, 680, 330))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktTableWidget.sizePolicy().hasHeightForWidth())
        self.pktTableWidget.setSizePolicy(sizePolicy)
        self.pktTableWidget.setRowCount(0)
        self.pktTableWidget.setObjectName(_fromUtf8("pktTableWidget"))
        self.pktTableWidget.setColumnCount(7)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(6, item)
        self.pktTableWidget.horizontalHeader().setVisible(True)
        self.pktTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.pktTableWidget.verticalHeader().setVisible(False)
        self.pktTreeWidget = QtGui.QTreeWidget(self.pktGroupBox)
        self.pktTreeWidget.setGeometry(QtCore.QRect(10, 370, 340, 221))
        self.pktTreeWidget.setObjectName(_fromUtf8("pktTreeWidget"))
        self.pktTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.pkt0xBrowser = QtGui.QTextBrowser(self.pktGroupBox)
        self.pkt0xBrowser.setGeometry(QtCore.QRect(360, 370, 190, 221))
        self.pkt0xBrowser.setObjectName(_fromUtf8("pkt0xBrowser"))
        self.pktAsciiBrowser = QtGui.QTextBrowser(self.pktGroupBox)
        self.pktAsciiBrowser.setGeometry(QtCore.QRect(559, 370, 131, 220))
        self.pktAsciiBrowser.setObjectName(_fromUtf8("pktAsciiBrowser"))
        self.filterGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.filterGroupBox.setGeometry(QtCore.QRect(250, 11, 701, 61))
        self.filterGroupBox.setObjectName(_fromUtf8("filterGroupBox"))
        self.filterLineEdit = QtGui.QLineEdit(self.filterGroupBox)
        self.filterLineEdit.setGeometry(QtCore.QRect(20, 30, 281, 22))
        self.filterLineEdit.setObjectName(_fromUtf8("filterLineEdit"))
        self.filterApplyButton = QtGui.QPushButton(self.filterGroupBox)
        self.filterApplyButton.setGeometry(QtCore.QRect(310, 26, 101, 32))
        self.filterApplyButton.setObjectName(_fromUtf8("filterApplyButton"))
        self.filterClearButton = QtGui.QPushButton(self.filterGroupBox)
        self.filterClearButton.setGeometry(QtCore.QRect(410, 26, 101, 32))
        self.filterClearButton.setObjectName(_fromUtf8("filterClearButton"))
        self.filterMsgLable = QtGui.QLabel(self.filterGroupBox)
        self.filterMsgLable.setGeometry(QtCore.QRect(520, 32, 141, 16))
        self.filterMsgLable.setText(_fromUtf8(""))
        self.filterMsgLable.setObjectName(_fromUtf8("filterMsgLable"))
        self.devGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.devGroupBox.setGeometry(QtCore.QRect(10, 10, 231, 71))
        self.devGroupBox.setObjectName(_fromUtf8("devGroupBox"))
        self.devLabel = QtGui.QLabel(self.devGroupBox)
        self.devLabel.setGeometry(QtCore.QRect(10, 35, 51, 20))
        self.devLabel.setObjectName(_fromUtf8("devLabel"))
        self.devComboBox = QtGui.QComboBox(self.devGroupBox)
        self.devComboBox.setGeometry(QtCore.QRect(60, 32, 161, 26))
        self.devComboBox.setObjectName(_fromUtf8("devComboBox"))
        self.optGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.optGroupBox.setGeometry(QtCore.QRect(10, 90, 231, 101))
        self.optGroupBox.setObjectName(_fromUtf8("optGroupBox"))
        self.promisCheckBox = QtGui.QCheckBox(self.optGroupBox)
        self.promisCheckBox.setGeometry(QtCore.QRect(20, 30, 151, 20))
        self.promisCheckBox.setObjectName(_fromUtf8("promisCheckBox"))
        self.stopButton = QtGui.QPushButton(self.optGroupBox)
        self.stopButton.setGeometry(QtCore.QRect(80, 60, 61, 32))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.startButton = QtGui.QPushButton(self.optGroupBox)
        self.startButton.setGeometry(QtCore.QRect(10, 60, 61, 32))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.clearButton = QtGui.QPushButton(self.optGroupBox)
        self.clearButton.setGeometry(QtCore.QRect(150, 60, 71, 32))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.statGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.statGroupBox.setGeometry(QtCore.QRect(10, 300, 231, 321))
        self.statGroupBox.setObjectName(_fromUtf8("statGroupBox"))
        self.totalLabel = QtGui.QLabel(self.statGroupBox)
        self.totalLabel.setGeometry(QtCore.QRect(10, 27, 41, 16))
        self.totalLabel.setObjectName(_fromUtf8("totalLabel"))
        self.totalCountLabel = QtGui.QLabel(self.statGroupBox)
        self.totalCountLabel.setGeometry(QtCore.QRect(70, 26, 61, 20))
        self.totalCountLabel.setText(_fromUtf8(""))
        self.totalCountLabel.setObjectName(_fromUtf8("totalCountLabel"))
        self.ethernetLabel = QtGui.QLabel(self.statGroupBox)
        self.ethernetLabel.setGeometry(QtCore.QRect(10, 50, 62, 16))
        self.ethernetLabel.setObjectName(_fromUtf8("ethernetLabel"))
        self.arpLabel = QtGui.QLabel(self.statGroupBox)
        self.arpLabel.setGeometry(QtCore.QRect(30, 70, 31, 16))
        self.arpLabel.setObjectName(_fromUtf8("arpLabel"))
        self.arpCountLabel = QtGui.QLabel(self.statGroupBox)
        self.arpCountLabel.setGeometry(QtCore.QRect(70, 70, 62, 16))
        self.arpCountLabel.setText(_fromUtf8(""))
        self.arpCountLabel.setObjectName(_fromUtf8("arpCountLabel"))
        self.rarpCountLabel = QtGui.QLabel(self.statGroupBox)
        self.rarpCountLabel.setGeometry(QtCore.QRect(80, 90, 62, 16))
        self.rarpCountLabel.setText(_fromUtf8(""))
        self.rarpCountLabel.setObjectName(_fromUtf8("rarpCountLabel"))
        self.rarpLabel = QtGui.QLabel(self.statGroupBox)
        self.rarpLabel.setGeometry(QtCore.QRect(30, 90, 41, 16))
        self.rarpLabel.setObjectName(_fromUtf8("rarpLabel"))
        self.ipLabel_2 = QtGui.QLabel(self.statGroupBox)
        self.ipLabel_2.setGeometry(QtCore.QRect(30, 110, 21, 16))
        self.ipLabel_2.setObjectName(_fromUtf8("ipLabel_2"))
        self.ipCountLabel = QtGui.QLabel(self.statGroupBox)
        self.ipCountLabel.setGeometry(QtCore.QRect(60, 110, 62, 16))
        self.ipCountLabel.setText(_fromUtf8(""))
        self.ipCountLabel.setObjectName(_fromUtf8("ipCountLabel"))
        self.ipv6Label_2 = QtGui.QLabel(self.statGroupBox)
        self.ipv6Label_2.setGeometry(QtCore.QRect(30, 130, 35, 16))
        self.ipv6Label_2.setObjectName(_fromUtf8("ipv6Label_2"))
        self.ipv6CountLabel = QtGui.QLabel(self.statGroupBox)
        self.ipv6CountLabel.setGeometry(QtCore.QRect(70, 130, 62, 16))
        self.ipv6CountLabel.setText(_fromUtf8(""))
        self.ipv6CountLabel.setObjectName(_fromUtf8("ipv6CountLabel"))
        self.internetLabel = QtGui.QLabel(self.statGroupBox)
        self.internetLabel.setGeometry(QtCore.QRect(10, 150, 62, 16))
        self.internetLabel.setObjectName(_fromUtf8("internetLabel"))
        self.tcpLabel = QtGui.QLabel(self.statGroupBox)
        self.tcpLabel.setGeometry(QtCore.QRect(30, 170, 31, 16))
        self.tcpLabel.setObjectName(_fromUtf8("tcpLabel"))
        self.tcpCountLabel = QtGui.QLabel(self.statGroupBox)
        self.tcpCountLabel.setGeometry(QtCore.QRect(70, 170, 62, 16))
        self.tcpCountLabel.setText(_fromUtf8(""))
        self.tcpCountLabel.setObjectName(_fromUtf8("tcpCountLabel"))
        self.udpLabel = QtGui.QLabel(self.statGroupBox)
        self.udpLabel.setGeometry(QtCore.QRect(30, 190, 33, 16))
        self.udpLabel.setObjectName(_fromUtf8("udpLabel"))
        self.udpCountLabel = QtGui.QLabel(self.statGroupBox)
        self.udpCountLabel.setGeometry(QtCore.QRect(70, 190, 62, 16))
        self.udpCountLabel.setText(_fromUtf8(""))
        self.udpCountLabel.setObjectName(_fromUtf8("udpCountLabel"))
        self.icmpLabel = QtGui.QLabel(self.statGroupBox)
        self.icmpLabel.setGeometry(QtCore.QRect(30, 210, 41, 16))
        self.icmpLabel.setObjectName(_fromUtf8("icmpLabel"))
        self.icmpCountLabel = QtGui.QLabel(self.statGroupBox)
        self.icmpCountLabel.setGeometry(QtCore.QRect(80, 210, 62, 16))
        self.icmpCountLabel.setText(_fromUtf8(""))
        self.icmpCountLabel.setObjectName(_fromUtf8("icmpCountLabel"))
        self.igmpCountLabel = QtGui.QLabel(self.statGroupBox)
        self.igmpCountLabel.setGeometry(QtCore.QRect(80, 230, 62, 16))
        self.igmpCountLabel.setText(_fromUtf8(""))
        self.igmpCountLabel.setObjectName(_fromUtf8("igmpCountLabel"))
        self.igmpLabel = QtGui.QLabel(self.statGroupBox)
        self.igmpLabel.setGeometry(QtCore.QRect(30, 230, 41, 16))
        self.igmpLabel.setObjectName(_fromUtf8("igmpLabel"))
        self.othersLabel = QtGui.QLabel(self.statGroupBox)
        self.othersLabel.setGeometry(QtCore.QRect(10, 270, 51, 16))
        self.othersLabel.setObjectName(_fromUtf8("othersLabel"))
        self.othersCountLabel = QtGui.QLabel(self.statGroupBox)
        self.othersCountLabel.setGeometry(QtCore.QRect(70, 270, 61, 20))
        self.othersCountLabel.setText(_fromUtf8(""))
        self.othersCountLabel.setObjectName(_fromUtf8("othersCountLabel"))
        self.icmpv6Label = QtGui.QLabel(self.statGroupBox)
        self.icmpv6Label.setGeometry(QtCore.QRect(30, 250, 51, 16))
        self.icmpv6Label.setObjectName(_fromUtf8("icmpv6Label"))
        self.icmpv6CountLabel = QtGui.QLabel(self.statGroupBox)
        self.icmpv6CountLabel.setGeometry(QtCore.QRect(90, 250, 62, 16))
        self.icmpv6CountLabel.setText(_fromUtf8(""))
        self.icmpv6CountLabel.setObjectName(_fromUtf8("icmpv6CountLabel"))
        self.errorCountLabel = QtGui.QLabel(self.statGroupBox)
        self.errorCountLabel.setGeometry(QtCore.QRect(60, 290, 61, 20))
        self.errorCountLabel.setText(_fromUtf8(""))
        self.errorCountLabel.setObjectName(_fromUtf8("errorCountLabel"))
        self.errorLabel = QtGui.QLabel(self.statGroupBox)
        self.errorLabel.setGeometry(QtCore.QRect(10, 290, 51, 16))
        self.errorLabel.setObjectName(_fromUtf8("errorLabel"))
        self.dumpGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.dumpGroupBox.setGeometry(QtCore.QRect(10, 200, 231, 91))
        self.dumpGroupBox.setObjectName(_fromUtf8("dumpGroupBox"))
        self.importButton = QtGui.QPushButton(self.dumpGroupBox)
        self.importButton.setGeometry(QtCore.QRect(20, 27, 90, 32))
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.exportButton = QtGui.QPushButton(self.dumpGroupBox)
        self.exportButton.setGeometry(QtCore.QRect(120, 27, 90, 32))
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.dumpLabel = QtGui.QLabel(self.dumpGroupBox)
        self.dumpLabel.setGeometry(QtCore.QRect(10, 60, 210, 16))
        self.dumpLabel.setText(_fromUtf8(""))
        self.dumpLabel.setObjectName(_fromUtf8("dumpLabel"))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QSniffer", None, QtGui.QApplication.UnicodeUTF8))
        self.pktGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Packets", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Protocol", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.filterGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.filterApplyButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.filterClearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.devGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.devLabel.setText(QtGui.QApplication.translate("MainWindow", "Device:", None, QtGui.QApplication.UnicodeUTF8))
        self.optGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.promisCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Promiscuous Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.statGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.totalLabel.setText(QtGui.QApplication.translate("MainWindow", "Total: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ethernetLabel.setText(QtGui.QApplication.translate("MainWindow", "Ethernet:", None, QtGui.QApplication.UnicodeUTF8))
        self.arpLabel.setText(QtGui.QApplication.translate("MainWindow", "ARP: ", None, QtGui.QApplication.UnicodeUTF8))
        self.rarpLabel.setText(QtGui.QApplication.translate("MainWindow", "RARP: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ipLabel_2.setText(QtGui.QApplication.translate("MainWindow", "IP: ", None, QtGui.QApplication.UnicodeUTF8))
        self.ipv6Label_2.setText(QtGui.QApplication.translate("MainWindow", "IPv6: ", None, QtGui.QApplication.UnicodeUTF8))
        self.internetLabel.setText(QtGui.QApplication.translate("MainWindow", "Internet:", None, QtGui.QApplication.UnicodeUTF8))
        self.tcpLabel.setText(QtGui.QApplication.translate("MainWindow", "TCP: ", None, QtGui.QApplication.UnicodeUTF8))
        self.udpLabel.setText(QtGui.QApplication.translate("MainWindow", "UDP: ", None, QtGui.QApplication.UnicodeUTF8))
        self.icmpLabel.setText(QtGui.QApplication.translate("MainWindow", "ICMP: ", None, QtGui.QApplication.UnicodeUTF8))
        self.igmpLabel.setText(QtGui.QApplication.translate("MainWindow", "IGMP: ", None, QtGui.QApplication.UnicodeUTF8))
        self.othersLabel.setText(QtGui.QApplication.translate("MainWindow", "Others: ", None, QtGui.QApplication.UnicodeUTF8))
        self.icmpv6Label.setText(QtGui.QApplication.translate("MainWindow", "ICMPv6: ", None, QtGui.QApplication.UnicodeUTF8))
        self.errorLabel.setText(QtGui.QApplication.translate("MainWindow", "Error: ", None, QtGui.QApplication.UnicodeUTF8))
        self.dumpGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Dump", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("MainWindow", "Import...", None, QtGui.QApplication.UnicodeUTF8))
        self.exportButton.setText(QtGui.QApplication.translate("MainWindow", "Export...", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

