# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/qinchenchong/workspace/QSniffer/QSniffer.ui'
#
# Created: Thu Oct 11 21:28:27 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 687)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.pktGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.pktGroupBox.setGeometry(QtCore.QRect(260, 60, 691, 611))
        self.pktGroupBox.setObjectName(_fromUtf8("pktGroupBox"))
        self.pktTableWidget = QtGui.QTableWidget(self.pktGroupBox)
        self.pktTableWidget.setGeometry(QtCore.QRect(10, 30, 671, 341))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pktTableWidget.sizePolicy().hasHeightForWidth())
        self.pktTableWidget.setSizePolicy(sizePolicy)
        self.pktTableWidget.setRowCount(0)
        self.pktTableWidget.setObjectName(_fromUtf8("pktTableWidget"))
        self.pktTableWidget.setColumnCount(6)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.pktTableWidget.setHorizontalHeaderItem(5, item)
        self.pktTableWidget.horizontalHeader().setVisible(True)
        self.pktTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.pktTableWidget.verticalHeader().setVisible(False)
        self.pktTreeWidget = QtGui.QTreeWidget(self.pktGroupBox)
        self.pktTreeWidget.setGeometry(QtCore.QRect(10, 380, 261, 221))
        self.pktTreeWidget.setObjectName(_fromUtf8("pktTreeWidget"))
        self.pktTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.pktTextBrowser = QtGui.QTextBrowser(self.pktGroupBox)
        self.pktTextBrowser.setGeometry(QtCore.QRect(280, 380, 401, 221))
        self.pktTextBrowser.setObjectName(_fromUtf8("pktTextBrowser"))
        self.filterGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.filterGroupBox.setGeometry(QtCore.QRect(260, 1, 691, 61))
        self.filterGroupBox.setObjectName(_fromUtf8("filterGroupBox"))
        self.filterLineEdit = QtGui.QLineEdit(self.filterGroupBox)
        self.filterLineEdit.setGeometry(QtCore.QRect(30, 30, 281, 22))
        self.filterLineEdit.setObjectName(_fromUtf8("filterLineEdit"))
        self.filterApplyButton = QtGui.QPushButton(self.filterGroupBox)
        self.filterApplyButton.setGeometry(QtCore.QRect(320, 26, 101, 32))
        self.filterApplyButton.setObjectName(_fromUtf8("filterApplyButton"))
        self.filterClearButton = QtGui.QPushButton(self.filterGroupBox)
        self.filterClearButton.setGeometry(QtCore.QRect(420, 26, 101, 32))
        self.filterClearButton.setObjectName(_fromUtf8("filterClearButton"))
        self.filterMsgLable = QtGui.QLabel(self.filterGroupBox)
        self.filterMsgLable.setGeometry(QtCore.QRect(530, 32, 141, 16))
        self.filterMsgLable.setText(_fromUtf8(""))
        self.filterMsgLable.setObjectName(_fromUtf8("filterMsgLable"))
        self.devGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.devGroupBox.setGeometry(QtCore.QRect(10, 0, 241, 191))
        self.devGroupBox.setObjectName(_fromUtf8("devGroupBox"))
        self.devLabel = QtGui.QLabel(self.devGroupBox)
        self.devLabel.setGeometry(QtCore.QRect(10, 30, 51, 20))
        self.devLabel.setObjectName(_fromUtf8("devLabel"))
        self.devComboBox = QtGui.QComboBox(self.devGroupBox)
        self.devComboBox.setGeometry(QtCore.QRect(60, 27, 161, 26))
        self.devComboBox.setObjectName(_fromUtf8("devComboBox"))
        self.descLabel = QtGui.QLabel(self.devGroupBox)
        self.descLabel.setGeometry(QtCore.QRect(10, 57, 81, 16))
        self.descLabel.setObjectName(_fromUtf8("descLabel"))
        self.optGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.optGroupBox.setGeometry(QtCore.QRect(10, 190, 241, 101))
        self.optGroupBox.setObjectName(_fromUtf8("optGroupBox"))
        self.promisCheckBox = QtGui.QCheckBox(self.optGroupBox)
        self.promisCheckBox.setGeometry(QtCore.QRect(20, 30, 151, 20))
        self.promisCheckBox.setObjectName(_fromUtf8("promisCheckBox"))
        self.stopButton = QtGui.QPushButton(self.optGroupBox)
        self.stopButton.setGeometry(QtCore.QRect(80, 60, 61, 32))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.startButton = QtGui.QPushButton(self.optGroupBox)
        self.startButton.setGeometry(QtCore.QRect(10, 60, 61, 32))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.clearButton = QtGui.QPushButton(self.optGroupBox)
        self.clearButton.setGeometry(QtCore.QRect(150, 60, 71, 32))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.statGroupBox = QtGui.QGroupBox(self.centralWidget)
        self.statGroupBox.setGeometry(QtCore.QRect(10, 290, 241, 241))
        self.statGroupBox.setObjectName(_fromUtf8("statGroupBox"))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "QSniffer", None, QtGui.QApplication.UnicodeUTF8))
        self.pktGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Packets", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Protocol", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pktTableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.filterGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.filterApplyButton.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.filterClearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.devGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.devLabel.setText(QtGui.QApplication.translate("MainWindow", "Device:", None, QtGui.QApplication.UnicodeUTF8))
        self.descLabel.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.optGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.promisCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Promiscuous Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.statGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

